name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - run: git config --system core.longpaths true
        if: runner.os == 'Windows'
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-bin: "false"
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - name: Install
        run: just install
      - name: Check
        run: just check
      - name: Test
        run: just test
      - name: Test with coverage
        run: just test-coverage
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          files: covertura.xml
          fail_ci_if_error: true
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          files: target/nextest/default/junit.xml
          report_type: test_results
          fail_ci_if_error: true
          skip_validation: true # https://github.com/codecov/codecov-action/issues/1876
      - name: Format
        run: just fmt
      - run: git add . && git diff
      - run: git diff --cached
      - name: Ensure no files have changed
        run: git add . && git diff --quiet && git diff --cached --quiet
